- name: "chmod bashrc"
  become: yes
  become_user: root
  file:
    path: /home/isucon/.bashrc
    mode: 0666

- name: Install Package(Build)
  become: yes
  become_user: root
  apt:
    name: 
    - libssl-dev
    - libreadline-dev
    - gcc
    - make
    - libffi-dev
    - zlib1g-dev
    - unzip
    update_cache: yes

- name: install xbuild
  become: yes
  become_user: root
  git:
    repo: https://github.com/mikiya771/xbuild.git
    dest: /tmp/xbuild
    version: master

- name: Install Go 1.17.2
  become: yes
  become_user: root
  command: /tmp/xbuild/go-install 1.17.2 /usr/local/go

- name: Add PATH for Go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    dest: &bash_aliases /home/isucon/.bashrc
    content: |
      export PATH=/usr/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/usr/local/go

- name: Install Node v18.2.0
  become: yes
  become_user: root
  command: /tmp/xbuild/node-install v18.2.0 /usr/local/node


- name: Add PATH for Node
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Node"
    dest: *bash_aliases 
    content: |
      export PATH=/usr/local/node/bin:$PATH

- name: Install Python v3.9.5
  become: yes
  become_user: root
  command: /tmp/xbuild/python-install 3.9.5 /usr/local/python
- name: Add PATH for Python
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Python"
    dest: *bash_aliases
    content: |
      export PATH=/usr/local/python/bin:$PATH
- name: Install Java 17
  become: yes
  become_user: root
  apt:
    name:
    - openjdk-17-jdk

- name: Download and Unzip Maven 3.8.4
  become: yes
  become_user: root
  unarchive:
    src: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
    dest: /opt
    remote_src: yes

- name: install Maven 3.8.4
  become: yes
  become_user: root
  command: ln -s /opt/apache-maven-3.8.6 /usr/bin/maven

- name: Add PATH for Mvn
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Maaven"
    dest: *bash_aliases
    content: |
      export PATH=/usr/bin/maven/bin:$PATH
