
---
- name: bench build
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/r-isucon/bench
  environment: &env
    PATH: "/home/isucon/bin:/home/isucon/.local/bin:/usr/local/node/bin:/usr/local/ruby/bin:/usr/local/go/bin:/home/isucon/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin"
  command: make

- name: Extension Ephemeral port
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.conf"
  with_items:
    - name: net.ipv4.ip_local_port_range
      value: "20000  65000"
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.tcp_fin_timeout
      value: "30"
    - name: net.ipv4.tcp_max_syn_backlog
      value: "2048"
    - name: net.core.somaxconn
      value: "2048"
