/* tslint:disable */
/* eslint-disable */
/**
 * R-ISUCON 2021 Summer
 * API mock for R-ISUCON 2021 Summer r-calendar
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
